name: fusesoc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile latest verilator
      run: |
        sudo apt-get update
        sudo apt-get install git perl python3 make autoconf g++ flex bison ccache libgoogle-perftools-dev libfl2 libfl-dev zlibc zlib1g zlib1g-dev
        git clone https://github.com/verilator/verilator
        cd verilator
        autoconf
        ./configure
        make -j `nproc`
        sudo make install

    - name: Install fusesoc
      run: sudo pip3 install fusesoc

    - name: Run Lint
      run: fusesoc --cores-root=. run --target=lint --setup --build --run qian-gu::dic_template

    - name: Run Simulation
      run: fusesoc --cores-root=. run --target=sim --setup --build --run qian-gu::dic_template
