name: verilator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Compile latest verilator
      run: |
        sudo apt-get update
        sudo apt-get install git perl python3 make autoconf g++ flex bison ccache libgoogle-perftools-dev libfl2 libfl-dev zlibc zlib1g zlib1g-dev
        git clone https://github.com/verilator/verilator
        cd verilator
        autoconf
        ./configure
        make -j `nproc`
        sudo make install
        
    - name: Install lcov
      run: sudo apt-get install lcov
      
    - name: Show configuration
      run: make show-config
      
    - name: Run verialte and coverage
      run: make run
      
    - name: Generate coverage result in html
      run: make genhtml
      
    - name: clean
      run: make clean
